### PR TITLE
Add markdownlint to CI action

### LINKED ISSUE #13: Add mdlint to CI
We have a bit of markdown now, and the amount will increase over time.

This is helpful to avoid frustrating formatting diffs and surprising rendering.

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #13.

This adds a new step to the CI workflow which runs [markdownlint](https://github.com/DavidAnson/markdownlint).

I copied it [from bevy](https://github.com/bevyengine/bevy/blob/ae580e58dd1d8539e26a44a4d428e1aa45a3d6f9/.github/workflows/ci.yml#L184-L198) for the most part, with some adjustments:
- Added a `name` for consistency with the other CI steps.
- Removed dependency on `check-missing-examples-in-docs`, because we don't have that.
- Replaced the `.markdown-lint.yml` rule template with the one from the [official templates](https://github.com/github/super-linter/blob/main/TEMPLATES/.markdown-lint.yml), so that it links to the rules and provides some examples. I commented out the example rules, although I'm not sure if that was necessary due to the `---` usage at the start of the file?

Open questions:
- Does it actually work? I'm not sure if it requires any additional configuration.
- Does the `if: always()` do anything or can it be removed?

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Seems to work. Feel free to add a violation in a temporary commit to double-check.

> Does the if: always() do anything or can it be removed?

I'm pretty sure this can be removed.

**Comment by TimJentzsch** [comment]
Maybe the `.markdown-lint.yml` completely overrides the defaults, so no rules are activated at the moment?

**Comment by TimJentzsch** [comment]
Or the checkout didn't work properly.
From [the logs](https://github.com/DioxusLabs/stretch/runs/6391697348?check_suite_focus=true):

```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

**Comment by alice-i-cecile** [comment]
That error message is normal, unfortunately. They want credentials to be able to inspect the git tree and optimize the checks done. Bevy doesn't think it's worth the security exposure, and I tend to agree.

**Comment by TimJentzsch** [comment]
What about the warnings that it doesn't seem to detect?

For example, I locally get

```
MD022/blanks-around-headings/blanks-around-headers: Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below]markdownlint[MD022](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md022)
```
which does not seem to fail the CI check.

**Pull request merged**
