### PR TITLE
Add CI jobs for checking and testing with no default features

### LINKED ISSUE #32: Add CI for no_std compilation and tests
As discussed in #23, we need to be sure that this continues to work.

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #32.

This PR adds two new jobs to the CI workflow to `cargo check` and `cargo test` with the `--no-default-features` flag. Currently this has mainly the effect of enabling `no_std`.

Notably these currently throw errors, which just highlights the need to include it in CI.

I'm not sure if I'm able to resolve these errors as I've never worked with `no_std` before, but I can certainly try :)

Side note: Why do we have both `cargo check` and `cargo test` jobs? Wouldn't `cargo test` always fail if `cargo check` fails?

**TODO**:
- [x] Fix errors from migrating to `heapless@0.7.9`
- [x] Fix errors from migrate to `arrayvec@0.7.2`
- [x] Add CI checks/tests with `--no-default-features --features alloc` flags

⚠️ **This is a breaking change!** (I think) ⚠️

The fixes to the no-default-feature configuration is probably a breaking change.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
> Notably these currently throw errors, which just highlights the need to include it in CI.

Yeah, I saw an existing bug on `stretch` about this, and I'm very happy to see CI fail here.

>  Why do we have both cargo check and cargo test jobs? Wouldn't cargo test always fail if cargo check fails?

As a reviewer, it can be quite useful to tell at a glance the current state of a PR. Tests failing is less severe than compilation failures, which are less severe than things like clippy or formatting violations.

**Comment by TimJentzsch** [comment]
Four of these errors are caused by a dependency upgrade which was part of #1. The `heapless` crate has removed the `heapless::consts` module ([changelog](https://github.com/japaric/heapless/blob/master/CHANGELOG.md#v070---2021-04-23)), which is used multiple times when the `alloc` and `std` features are disabled.

Should we first downgrade `heapless` again and properly upgrade in a new issue/PR or should this be fixed here?

**Comment by TimJentzsch** [comment]
Two more errors are also caused by a dependency upgrade, `arrayvec` doesn't have the `Array` trait anymore and changed the `ArrayVec` definition.

**Comment by alice-i-cecile** [comment]
I'd like to fix these issues here; the dependency upgrade was good for other reasons, and the fix should be self-contained.

**Comment by mockersf** [comment]
> This PR adds two new jobs to the CI workflow to `cargo check` and `cargo test` with the `--no-default-features` flag. Currently this has mainly the effect of enabling `no_std`.

Could you also add those for `--no-default-features --features alloc`? It's the other feature that was tested by the original crate.

> Side note: Why do we have both `cargo check` and `cargo test` jobs? Wouldn't `cargo test` always fail if `cargo check` fails?

I added the CI by copying [this quickstart](https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md) because I wanted something quick to setup to make sure tests would be kept green

**Comment by TimJentzsch** [comment]
This is now ready to review. Please take extra care while reviewing my fixes to the compile errors, I didn't really know what I was doing while converting the libraries to constant generics.

I think renaming the CI jobs also messed up the required checks, we might need to change the settings there (or change the names back).

**Review by alice-i-cecile — APPROVED** [review]
Looks great; that's a nice little application of const generics.

**Comment by TimJentzsch** [comment]
We probably need to bump a minor version for this, because it's probably a breaking change, right? Should I change the version in the `Cargo.toml` file or how is this usually handled?

**Pull request merged**
