### PR TITLE
Fix Markdown linting in CI

### PR DESCRIPTION
**Pull request by alice-i-cecile**
As discussed with @TimJentzsch in #13, the md-lint job doesn't seem to be picking up on violations correctly.

This PR is an attempt to fix that; it will be quite incremental, as we wait for the CI to fail correctly.

### CODE REVIEW

**Comment by TimJentzsch** [comment]
Since I copied most of it from bevy, are we sure that it works correctly there?

**Comment by alice-i-cecile** [comment]
Hmm. I'm pretty sure I've had it complain at me in the past. The setup [here](https://github.com/bevyengine/bevy-website/blob/7958aff89bdc33158cc56717dec9d40baaddf453/.github/workflows/ci.yml#L38) is definitely working; I spent way too long fixing the errors it caught.

**Comment by TimJentzsch** [comment]
Was that before or after you removed the CI token there? Maybe it's needed after all?

**Comment by TimJentzsch** [comment]
I changed it from `main` to `master`, because I think we're using `master` on this repo.

**Comment by alice-i-cecile** [comment]
Yeah, doesn't appear to be the issue. Let me check the logs and docs more carefully.

**Comment by mockersf** [comment]
`VALIDATE_ALL_CODEBASE` is set to false. that means it only runs on files modified in the PR

**Comment by alice-i-cecile** [comment]
> [WARN]   No files were found in the GITHUB_WORKSPACE:[/github/workspace] to lint!

https://github.com/DioxusLabs/stretch/runs/6392533237?check_suite_focus=true#step:4:73

Well, that would appear to be our problem.

**Comment by alice-i-cecile** [comment]
Excellent; CI is properly failing. I'll fix up the violations next.

**Review by TimJentzsch — APPROVED** [review]

**Review by TimJentzsch — APPROVED** [review]

**Comment by TimJentzsch** [comment]
@alice-i-cecile Looks like CI is failing due to the maximum line length, do you want to fix that or should we remove that check entirely?

**Comment by alice-i-cecile** [comment]
I'll fix it up. It's a useful lint (in moderation): the really long lines produce ugly git diffs.

**Pull request merged**
